import {
  ArrowLeftIcon,
  ArrowUpIcon,
  BookBookmarkIcon,
  BookOpenIcon,
  ChartColumnIcon,
  ChevronDownIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  ClockIcon,
  CloudUploadIcon,
  FileIcon,
  FileQuestionMarkIcon,
  FilesIcon,
  FileTextIcon,
  LoaderCircleIcon,
  LogOutIcon,
  MailCheckIcon,
  MenuIcon,
  MessagesSquareIcon,
  PanelLeftIcon,
  PencilIcon,
  PlusIcon,
  RefreshCwIcon,
  SearchIcon,
  SearchXIcon,
  SparklesIcon,
  SquareIcon,
  SquarePenIcon,
  TagIcon,
  Trash2Icon,
  TriangleAlertIcon,
  UploadIcon,
  UserRoundIcon,
  XIcon,
} from 'lucide-react'

/** The app's icon vocabulary; components refer to icons by name so the set stays consistent. */
export const icons = {
  brand: BookBookmarkIcon,
  documents: FileTextIcon,
  chat: MessagesSquareIcon,
  usage: ChartColumnIcon,
  menu: MenuIcon,
  user: UserRoundIcon,
  signOut: LogOutIcon,
  error: TriangleAlertIcon,
  notFound: FileQuestionMarkIcon,
  inbox: MailCheckIcon,
  back: ArrowLeftIcon,
  add: PlusIcon,
  upload: UploadIcon,
  dropFile: CloudUploadIcon,
  file: FileIcon,
  search: SearchIcon,
  noMatches: SearchXIcon,
  tag: TagIcon,
  remove: XIcon,
  delete: Trash2Icon,
  reindex: RefreshCwIcon,
  statusPending: ClockIcon,
  statusProcessing: LoaderCircleIcon,
  statusReady: CircleCheckIcon,
  statusFailed: CircleAlertIcon,
  newChat: SquarePenIcon,
  conversations: PanelLeftIcon,
  send: ArrowUpIcon,
  stop: SquareIcon,
  rename: PencilIcon,
  sources: BookOpenIcon,
  expand: ChevronDownIcon,
  scope: FilesIcon,
  ask: SparklesIcon,
} as const

export type IconName = keyof typeof icons
