import type { ProviderId } from './provider-ids.js'
import type { ProviderProfile } from './provider-profiles.types.js'

// gemini-embedding-001 returns 3072 values natively; 1536 fits the vector(1536) column (DEC-014).
const GEMINI_EMBEDDING_DIMENSIONS = 1536

/** Built-in knowledge per provider; every value here can be overridden through `AiConfig`. */
export const PROVIDER_PROFILES: Readonly<Record<ProviderId, ProviderProfile>> = {
  openai: {
    id: 'openai',
    label: 'OpenAI',
    defaultBaseUrl: 'https://api.openai.com/v1',
    requiresApiKey: true,
    defaultChatModel: 'gpt-4o-mini',
    defaultEmbeddingModel: 'text-embedding-3-small',
    supportsEmbeddings: true,
    supportsStreamUsage: true,
    supportsEmbeddingDimensions: true,
    maxTokensParam: 'max_completion_tokens',
  },
  groq: {
    id: 'groq',
    label: 'Groq',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    requiresApiKey: true,
    defaultChatModel: 'llama-3.3-70b-versatile',
    supportsEmbeddings: false,
    supportsStreamUsage: true,
    supportsEmbeddingDimensions: false,
    maxTokensParam: 'max_tokens',
  },
  together: {
    id: 'together',
    label: 'Together AI',
    defaultBaseUrl: 'https://api.together.xyz/v1',
    requiresApiKey: true,
    defaultChatModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    defaultEmbeddingModel: 'BAAI/bge-base-en-v1.5',
    supportsEmbeddings: true,
    supportsStreamUsage: true,
    supportsEmbeddingDimensions: false,
    maxTokensParam: 'max_tokens',
  },
  openrouter: {
    id: 'openrouter',
    label: 'OpenRouter',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    requiresApiKey: true,
    defaultChatModel: 'openai/gpt-4o-mini',
    defaultEmbeddingModel: 'openai/text-embedding-3-small',
    supportsEmbeddings: true,
    supportsStreamUsage: true,
    supportsEmbeddingDimensions: false,
    maxTokensParam: 'max_tokens',
    attributionHeaders: { appName: 'X-Title', appUrl: 'HTTP-Referer' },
  },
  gemini: {
    id: 'gemini',
    label: 'Google Gemini',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    requiresApiKey: true,
    defaultChatModel: 'gemini-3.5-flash-lite',
    defaultEmbeddingModel: 'gemini-embedding-001',
    defaultEmbeddingDimensions: GEMINI_EMBEDDING_DIMENSIONS,
    supportsEmbeddings: true,
    supportsStreamUsage: true,
    supportsEmbeddingDimensions: true,
    maxTokensParam: 'max_completion_tokens',
  },
  ollama: {
    id: 'ollama',
    label: 'Ollama',
    defaultBaseUrl: 'http://localhost:11434/v1',
    requiresApiKey: false,
    placeholderApiKey: 'ollama',
    defaultChatModel: 'llama3.2',
    defaultEmbeddingModel: 'nomic-embed-text',
    supportsEmbeddings: true,
    supportsStreamUsage: true,
    supportsEmbeddingDimensions: false,
    maxTokensParam: 'max_tokens',
  },
  custom: {
    id: 'custom',
    label: 'Custom OpenAI-compatible server',
    requiresApiKey: false,
    placeholderApiKey: 'not-needed',
    supportsEmbeddings: true,
    supportsStreamUsage: true,
    supportsEmbeddingDimensions: false,
    maxTokensParam: 'max_tokens',
  },
}
