import { nestConfig } from '@kb/eslint-config/nest'
import { defineConfig, globalIgnores } from 'eslint/config'

// Generated by `pnpm db:types`; never edited by hand.
export default defineConfig(globalIgnores(['src/database/database.types.ts']), nestConfig)
